### ISSUE TITLE
mRNA_cell value unknown for some cell types: CAFs, Endothelial...

### ISSUE THREAD

**Issue by bhinderb** [GfellerLab/EPIC#10]
Hi - I get a warning message when running EPIC (input dataset is TCGA RNAseq FPKM). Please advise on a resolution.

Warning message:
In EPIC(bulk = bulkSamplesMatrix) :
  mRNA_cell value unknown for some cell types: CAFs, Endothelial - using the default value of 0.4 for these but this might bias the true cell proportions from all cell types.

**Comment by jracle85** [comment]
Hello,
This is indicated in the the FAQ part of the README:
[https://github.com/GfellerLab/EPIC#what-is-the-meaning-of-the-warning-message-telling-that-some-mrna_cell-values-are-unknown](https://github.com/GfellerLab/EPIC#what-is-the-meaning-of-the-warning-message-telling-that-some-mrna_cell-values-are-unknown)
Best regards,
Julien
