### ISSUE TITLE
other cells

### ISSUE THREAD

**Issue by marceaf23** [GfellerLab/EPIC#3]
Hi,

The software is great but I am still confused on what cells are in other cells? can normal cells also be mixed in there with cancer cells or is it assumed that the "other cells" portion is all cancer cells?

**Comment by jracle85** [comment]
Hello,

Thanks for your interest in EPIC.
So the other cells correspond to all the cell types that are not part of the reference samples.
If you use our defined reference profiles, we defined most of the cell types that should be found in a tumor (except the cancer cells and the normal cells from which the cancer developed as these other normal cells aren't much different from the cancer cells). Therefore it can be assumed that the "other cells" are a good proxy for the proportion of the true cancer cells.

If you use your own reference profiles or use EPIC on non-tumor bulk samples, then the "other cells" will reflect the various cell types that are present in this bulk but not defined by the reference profiles.

I hope this helps!

Cheers,

Julien
