### ISSUE TITLE
Custom Signature genes

### ISSUE THREAD

**Issue by Disha770** [GfellerLab/EPIC#7]
Hi,
I was wondering if I can provide a custom signature gene file in epic?
If yes then can you tell me how can I do that ?
Thank you in advance.

**Comment by jracle85** [comment]
Hi Disha,

Yes, you can define your own gene expression reference profiles and genes signatures to use with them.

This corresponds to the input option called *reference*. You can check the help page of EPIC for details (browse to it with e.g. `?EPIC::EPIC` from within R).  And you can see examples of such references in `EPIC::TRef` for example.

Best wishes,

Julien

**Comment by Disha770** [comment]
Hi,
Thank you for your suggestion but can I add my own signature genes to the TRef?

**Comment by jracle85** [comment]
Hello,
If you want to use your own gene signature to use with the reference profiles TRef, you can use the option `sigGenes` from EPIC, with a character vector giving the gene names to use as signature (it replaces the ones used by default for TRef, it doesn't add them - to add them, just add the ones given in `EPIC::TRef$sigGenes` to your list).
Best regards,
Julien
