### ISSUE TITLE
Error: processing vignette 'EPIC.Rmd' failed with diagnostics:

### ISSUE THREAD

**Issue by JianGuoZhou3** [GfellerLab/EPIC#8]
````
 devtools::install_github("GfellerLab/EPIC", build_vignettes=TRUE)
Downloading GitHub repo GfellerLab/EPIC@HEAD
✓  checking for file ‘/private/var/folders/h1/wph5l7kn6sq020007z1bq2d00000gn/T/RtmpIhaNLF/remotese2c15a901700/GfellerLab-EPIC-dcdcbc5/DESCRIPTION’ (376ms)
─  preparing ‘EPIC’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (20.6s)
   --- re-building ‘EPIC.Rmd’ using rmarkdown
   dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
     Referenced from: /usr/local/bin/pandoc (which was built for Mac OS X 10.15)
     Expected in: /usr/lib/libSystem.B.dylib
   
   dyld: Symbol not found: ____chkstk_darwin
     Referenced from: /usr/local/bin/pandoc (which was built for Mac OS X 10.15)
     Expected in: /usr/lib/libSystem.B.dylib
   
   Error: processing vignette 'EPIC.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 6
   --- failed re-building ‘EPIC.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘EPIC.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'EPIC' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> 
E> Error: processing vignette 'EPIC.Rmd' failed with diagnostics:
E> pandoc document conversion failed with error 6
E> --- failed re-building ‘EPIC.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘EPIC.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
````

**Comment by JianGuoZhou3** [comment]
@jracle85

**Comment by jracle85** [comment]
Dear @jianguozhouzunyimedicaluniversity ,

I'm sorry that it didn't work to install EPIC and I'm sorry for the delay in reply; it's been very busy times...

I don't really know what is the issue that you're having. It seems to be an issue from "pandoc", which isn't part of EPIC. What you can try is to install EPIC with the following command:
`devtools::install_github("GfellerLab/EPIC", build_vignettes=FALSE)`

It should hopefully work. This won't however build the package vignette that contains some nicely formatted instructions on how to use EPIC and some FAQ about EPIC, but the rest of the help documentation of EPIC as well as EPIC in itself should then work.

If you need it, the package vignette (in non-compiled format) is available at https://github.com/GfellerLab/EPIC/blob/master/vignettes/EPIC.Rmd . You could then either use it as is, or try compiling it from within Rstudio for example, as indicated at https://bookdown.org/yihui/rmarkdown/compile.html (I'm not sure that this will work though, I didn't test it).

I hope this works like that! Best regards,

Julien

**Comment by JianGuoZhou3** [comment]
> Dear @jianguozhouzunyimedicaluniversity ,
> 
> I'm sorry that it didn't work to install EPIC and I'm sorry for the delay in reply; it's been very busy times...
> 
> I don't really know what is the issue that you're having. It seems to be an issue from "pandoc", which isn't part of EPIC. What you can try is to install EPIC with the following command:
> `devtools::install_github("GfellerLab/EPIC", build_vignettes=FALSE)`
> 
> It should hopefully work. This won't however build the package vignette that contains some nicely formatted instructions on how to use EPIC and some FAQ about EPIC, but the rest of the help documentation of EPIC as well as EPIC in itself should then work.
> 
> If you need it, the package vignette (in non-compiled format) is available at https://github.com/GfellerLab/EPIC/blob/master/vignettes/EPIC.Rmd . You could then either use it as is, or try compiling it from within Rstudio for example, as indicated at https://bookdown.org/yihui/rmarkdown/compile.html (I'm not sure that this will work though, I didn't test it).
> 
> I hope this works like that! Best regards,
> 
> Julien

Dear Julien, now it's worked, thx.
